#!/usr/bin/env python3
"""Emit a self-contained Base USDC pay card (EIP-681 + MetaMask + tip/unlock). Stdlib only."""
from __future__ import annotations

import argparse
import html
import json
import sys
from pathlib import Path

USDC_BASE = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
CHAIN_ID = 8453
DEFAULT_TO = "0xbAd41cF0f0d5442f9A53630F8081BFd257DA019b"
DEFAULT_TIP = "https://shieldz.cash/tip/tip-d2599a4d16a6f4b0"
DEFAULT_UNLOCK = "https://shieldz.cash/unlock/2B-pnOcAsqSdaw7IMmSL"


def atomic_usdc(amount: float) -> int:
    if amount <= 0:
        raise ValueError("amount must be > 0")
    return int(round(amount * 1_000_000))


def eip681(to: str, amount: float) -> str:
    return f"ethereum:{USDC_BASE}@{CHAIN_ID}/transfer?address={to}&uint256={atomic_usdc(amount)}"


def metamask_deeplink(uri: str) -> str:
    # MetaMask mobile deep link wrapper
    from urllib.parse import quote

    return f"https://metamask.app.link/send/{quote(uri, safe='')}"


def card_html(
    *,
    to: str,
    amount: float,
    title: str,
    tip: str,
    unlock: str,
) -> str:
    uri = eip681(to, amount)
    mm = metamask_deeplink(uri)
    basescan = f"https://basescan.org/address/{to}"
    t = html.escape(title)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>{t}</title>
<style>
  :root {{ color-scheme: light dark; font-family: system-ui, sans-serif; }}
  body {{ max-width: 40rem; margin: 2rem auto; padding: 0 1rem; line-height: 1.45; }}
  code, pre {{ font-size: 0.85rem; word-break: break-all; }}
  .box {{ border: 1px solid #8884; border-radius: 12px; padding: 1rem 1.1rem; margin: 1rem 0; }}
  a.btn {{ display: inline-block; margin: 0.35rem 0.35rem 0 0; padding: 0.55rem 0.9rem;
           border-radius: 10px; background: #0052ff; color: #fff; text-decoration: none; font-weight: 600; }}
  a.btn.alt {{ background: #0b0b0f; border: 1px solid #2a2a35; }}
  label {{ display: block; font-size: 0.85rem; opacity: 0.8; margin-top: 0.75rem; }}
  input {{ width: 100%; padding: 0.45rem 0.55rem; border-radius: 8px; border: 1px solid #8886; }}
</style>
</head>
<body>
  <h1>{t}</h1>
  <p>Pay <strong>${amount:g} USDC</strong> on <strong>Base</strong> to the treasury below. No API key. No custody.</p>
  <div class="box">
    <div><strong>Receive</strong></div>
    <code id="to">{html.escape(to)}</code>
    <label>Amount (USDC)</label>
    <input id="amt" type="number" min="0.01" step="0.01" value="{amount:g}"/>
    <p style="margin-top:0.9rem">
      <a class="btn" id="mm" href="{html.escape(mm)}" rel="noopener">Open in MetaMask</a>
      <a class="btn alt" id="tip" href="{html.escape(tip)}" rel="noopener" target="_blank">Tip jar</a>
      <a class="btn alt" id="unlock" href="{html.escape(unlock)}" rel="noopener" target="_blank">$5 unlock</a>
    </p>
    <label>EIP-681 URI</label>
    <pre id="uri">{html.escape(uri)}</pre>
    <p><a href="{html.escape(basescan)}" rel="noopener" target="_blank">Basescan</a> ·
       Coinbase Wallet: send USDC on Base manually to the address above.</p>
  </div>
  <p style="opacity:0.75;font-size:0.9rem">Generated by
    <a href="https://github.com/filip-study/base-usdc-pay-card">base-usdc-pay-card</a>
    · pairs with <a href="https://github.com/filip-study/base-usdc-paylink">paylink</a>
    + <a href="https://github.com/filip-study/base-usdc-tip-kit">tipcheck</a>.</p>
<script>
const USDC="0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913", CHAIN=8453, TO={json.dumps(to)};
const tip={json.dumps(tip)}, unlock={json.dumps(unlock)};
function atomic(a){{return Math.round(Number(a)*1e6);}}
function rebuild(){{
  const a=Number(document.getElementById("amt").value)||0;
  const uri=`ethereum:${{USDC}}@${{CHAIN}}/transfer?address=${{TO}}&uint256=${{atomic(a)}}`;
  document.getElementById("uri").textContent=uri;
  document.getElementById("mm").href="https://metamask.app.link/send/"+encodeURIComponent(uri);
}}
document.getElementById("amt").addEventListener("input", rebuild);
</script>
</body>
</html>
"""


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Emit a Base USDC pay card HTML file")
    p.add_argument("--to", default=DEFAULT_TO, help="Receive address on Base")
    p.add_argument("--amount", type=float, default=5.0, help="USDC amount")
    p.add_argument("--title", default="Base USDC pay card")
    p.add_argument("--tip", default=DEFAULT_TIP)
    p.add_argument("--unlock", default=DEFAULT_UNLOCK)
    p.add_argument("-o", "--out", default="-", help="Output path or - for stdout")
    p.add_argument("--json", action="store_true", help="Print link JSON instead of HTML")
    args = p.parse_args(argv)

    uri = eip681(args.to, args.amount)
    payload = {
        "to": args.to,
        "amount_usdc": args.amount,
        "atomic": atomic_usdc(args.amount),
        "eip681": uri,
        "metamask_deeplink": metamask_deeplink(uri),
        "tip": args.tip,
        "unlock": args.unlock,
        "basescan": f"https://basescan.org/address/{args.to}",
    }
    if args.json:
        text = json.dumps(payload, indent=2) + "\n"
    else:
        text = card_html(
            to=args.to,
            amount=args.amount,
            title=args.title,
            tip=args.tip,
            unlock=args.unlock,
        )
    if args.out == "-":
        sys.stdout.write(text)
    else:
        Path(args.out).write_text(text, encoding="utf-8")
        print(f"wrote {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
